### PR TITLE
added device "blind"

### PR DESCRIPTION
**Pull request by dirk777**
device "blind" is now handled

### CODE REVIEW

**Comment by dirk777** [comment]
you are right ;-) unites for blinds added and new lines at end of file removed

**Comment by Julius2342** [comment]
You removed too many lines :-) [I know flake and pylint are terribly picky ... ]

**Comment by dirk777** [comment]
ok, just to avoid further unnecessary commits, which lines do I need to add again

**Comment by Julius2342** [comment]
thank you! :)

(Will try to fix the failing python nightly build asap)

**Comment by Julius2342** [comment]
Hmm. looks like the broken python3.7 is a general issue of pyaml. Dozens of people are reporting the same problem :)

**Pull request merged**
