### PR TITLE
somfy dexxo smart io garage door support

### PR DESCRIPTION
**Pull request by otokarl**
This PR is to add support of [dexxo smart io](https://www.somfy.fr/produits/1216540/dexxo-smart-io-pack-confort).
Tested on my garage door installation.

### CODE REVIEW

**Comment by Julius2342** [comment]
some linting errors:

see: https://travis-ci.org/github/Julius2342/pyvlx/jobs/752130284

```
pyvlx/node_helper.py:94:6: C0303: Trailing whitespace (trailing-whitespace)

pyvlx/node_helper.py:95:0: W0311: Bad indentation. Found 5 spaces, expected 8 (bad-indentation)

pyvlx/node_helper.py:133:6: C0303: Trailing whitespace (trailing-whitespace)
```

and 

```
./pyvlx/node_helper.py:94:7: W291 trailing whitespace

./pyvlx/node_helper.py:95:6: E111 indentation is not a multiple of four

./pyvlx/node_helper.py:96:13: E126 continuation line over-indented for hanging indent

./pyvlx/node_helper.py:101:9: E121 continuation line under-indented for hanging indent

./pyvlx/node_helper.py:133:7: W291 trailing whitespace

./test/node_helper_test.py:234:10: W292 no newline at end of file


```

**Comment by otokarl** [comment]
> some linting errors:
> 
> see: https://travis-ci.org/github/Julius2342/pyvlx/jobs/752130284
> 
> ```
> pyvlx/node_helper.py:94:6: C0303: Trailing whitespace (trailing-whitespace)
> 
> pyvlx/node_helper.py:95:0: W0311: Bad indentation. Found 5 spaces, expected 8 (bad-indentation)
> 
> pyvlx/node_helper.py:133:6: C0303: Trailing whitespace (trailing-whitespace)
> ```
> 
> and
> 
> ```
> ./pyvlx/node_helper.py:94:7: W291 trailing whitespace
> 
> ./pyvlx/node_helper.py:95:6: E111 indentation is not a multiple of four
> 
> ./pyvlx/node_helper.py:96:13: E126 continuation line over-indented for hanging indent
> 
> ./pyvlx/node_helper.py:101:9: E121 continuation line under-indented for hanging indent
> 
> ./pyvlx/node_helper.py:133:7: W291 trailing whitespace
> 
> ./test/node_helper_test.py:234:10: W292 no newline at end of file
> ```

Ok, fixed now.
What is the next step?

**Comment by jirkapas** [comment]
Hi,
I don't want to be super annoying, but I would like to connect my Dexxo IO motor to Home Assistant. But the version of pyvlx that contains this update is not currently used by the Velux integration in Home Assistant. 
Can someone that knows what's they are doing create a Home Assistant pull request that would update pyvlx to version 0.2.19? Because I don't know what I'm doing when in comes to creating a proper pull request. 

Thanks a lot to anyone who would consider creating this pull request for me.

**Comment by Julius2342** [comment]
Thank you @tikismoke !

**Comment by jirkapas** [comment]
@tikismoke I also thank you. 😀

**Comment by tikismoke** [comment]
https://github.com/home-assistant/core/pull/49533#issuecomment-824413499
@jirkapas could you have a look?

**Comment by jirkapas** [comment]
> [home-assistant/core#49533 (comment)](https://github.com/home-assistant/core/pull/49533#issuecomment-824413499)
> @jirkapas could you have a look?

@tikismoke I'm not really a developer. But I checked some of the previous pyvlx dependency bump PR's and they all also changed the pyvlx version in requirements_all.txt. See: https://github.com/home-assistant/core/pull/42895/commits/afb6788ed9a7cbeaa5e800393794d2db7ee1bb75

**Pull request merged**
