### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tikismoke**
Adding dependencies on debian stretch at least.

### CODE REVIEW

**Comment by tikismoke** [comment]
Think it should be done by Pypy, but do not know how-to :(

**Comment by Julius2342** [comment]
I just found: https://pip.pypa.io/en/stable/user_guide/ ...

Probably we just have to add a "requirements.txt" within the package ...

**Comment by Julius2342** [comment]
May you have a look at: 1e9ca6a36132535e0efe5bbf10385d0300997012

**Comment by tikismoke** [comment]
Ok it solved it, i made:
```
git clone https://github.com/Julius2342/pyvlx
cd pyvlx/
git checkout roller-shutter
python3.5 setup.py install
```

And my own python script works as except and with roller-shutter Class too solving #2

**Pull request closed without merging**
