### PR TITLE
Accepting dual shutters and addressing them like regular single ones.

### PR DESCRIPTION
**Pull request by Arduous**
Signed-off-by: Samuel Progin <samuel.progin@gmail.com>

### CODE REVIEW

**Comment by Julius2342** [comment]
I fixed the pylint problem in master.

I only have one question: "Dual shutters", the name suggests that you are controlling two shutters?

**Comment by Arduous** [comment]
Sorry I missed the pylint one.

Yes! As shown in the attached picture the The Velux is split in two parts. The upper one can be opened, whereas the bottom one is fixed. There are two different shutters with their own motor, but they are seen as a single one from the controlling point of view. 

The first 50% address the upper shutter, and the last 50% the below one. 75% then mean the upper completely shut, and the below 50%.

To be fully exhaustive, I should mention that they can be individually addressed with a KLR-200 Control Pad, but this is not exposed through the KLF-200 bridge, even in scene mode.

**Comment by Julius2342** [comment]
Thank you for the explanation!

(It might be worth looking at the documentation and the internal values of the received messages. According to the documentation, current_position_fp1 contains the position of the upper curtain, current_position_fp2 of the lower curtain and current_position_fp3 the linear speed of the two curtains.)

**Comment by Arduous** [comment]
Thanks!

Interesting point. I'll have a look on this!

**Pull request merged**
