### PR TITLE
Reboot KLF200 on disconnect

### PR DESCRIPTION
**Pull request by pawlizio**
I think we should include the reboot function directly into KLF200 disconnect command. I know the KLF200 open it's WIFI Access Point on restart, however you need to have the creditentials to connect to this AP, so I think this solution can be justified as workaround.

This PR is a workaround to avoid #53, #68 and #30

### CODE REVIEW

**Comment by pawlizio** [comment]
@Julius2342 : What do think? Moreover, can you create a new release? Finally I could do that on my own, as you gave me the rights. However currently the upload to pypi is not automated and there I don't have the permissions. For this you could add an action to automatically upload to to pypi as described here: https://github.com/marketplace/actions/pypi-publish

**Comment by Julius2342** [comment]
If you tell me your pypi account id, i think i can add you ...

**Comment by pawlizio** [comment]
It's the same as here in github, pawlizio

**Comment by Julius2342** [comment]
Added you :)

**Pull request merged**
