### PR TITLE
timeout of api calls configurable

### PR DESCRIPTION
**Pull request by dirk777**
klf200 is responding after a request is fully handled again (e.g. running a scene is completed). Thus, a following request run into timeout, which needs to be made adjustable to users environment (e.g. a blind is running longer than a roller shutter)

### CODE REVIEW

**Comment by Julius2342** [comment]
What default do you use in your implementation? (The timeout of 10 seconds was picked by me more or less randomly)

**Comment by dirk777** [comment]
I need to take at least 60s, because my blinds take about 55sec to open/close completely

**Comment by Julius2342** [comment]
Wouldn't it make sense to have a shorter timeout and retry several times?

**Comment by dirk777** [comment]
from a usage point of view it makes sense not to bother framework user to find the right timeout. On the other hand side, I don't like try and error approaches. So the root cause is with velux as you mentioned before

**Pull request merged**
